// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqDWN-xjoQFGe_-KguZre8JUJmuaHSzpo',
    appId: '1:359425010864:web:bca6b02e7853e473979f75',
    messagingSenderId: '359425010864',
    projectId: 'learn-38ec4',
    authDomain: 'learn-38ec4.firebaseapp.com',
    storageBucket: 'learn-38ec4.appspot.com',
    measurementId: 'G-8KNQKMK8NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlkn96JP9vbECLa8bqtjYyq32IK0cddA',
    appId: '1:359425010864:android:f9526986574b1d28979f75',
    messagingSenderId: '359425010864',
    projectId: 'learn-38ec4',
    storageBucket: 'learn-38ec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbvd-YuUTj2-HpDFh1Ohqw4Or5nT3_stU',
    appId: '1:359425010864:ios:fada1ce20488daed979f75',
    messagingSenderId: '359425010864',
    projectId: 'learn-38ec4',
    storageBucket: 'learn-38ec4.appspot.com',
    androidClientId: '359425010864-4816nq6ridredh3fr9907b976q75idjj.apps.googleusercontent.com',
    iosClientId: '359425010864-954sgd3bbrsjrbk5g2ijl89og7ovsb8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbvd-YuUTj2-HpDFh1Ohqw4Or5nT3_stU',
    appId: '1:359425010864:ios:fada1ce20488daed979f75',
    messagingSenderId: '359425010864',
    projectId: 'learn-38ec4',
    storageBucket: 'learn-38ec4.appspot.com',
    androidClientId: '359425010864-4816nq6ridredh3fr9907b976q75idjj.apps.googleusercontent.com',
    iosClientId: '359425010864-954sgd3bbrsjrbk5g2ijl89og7ovsb8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgramclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqDWN-xjoQFGe_-KguZre8JUJmuaHSzpo',
    appId: '1:359425010864:web:f5ff06020bce6037979f75',
    messagingSenderId: '359425010864',
    projectId: 'learn-38ec4',
    authDomain: 'learn-38ec4.firebaseapp.com',
    storageBucket: 'learn-38ec4.appspot.com',
    measurementId: 'G-TMLDPXEMG6',
  );

}